name: archetypal
channels:
  - conda-forge
dependencies:
  - geopandas
  - networkx
  - six
  - matplotlib>=2.1
  - requests>=2.18
  - pycountry
  - scikit-learn
  - scipy
  - pandas==1.2.0
  - numpy>=1.17
  - tqdm
  - tabulate
  - path.py
  - pyomo
  - pint
  - click
  - outdated
  - pip
  - pip:
    - tsam
    - git+https://github.com/samuelduchesne/eppy.git@feature/defaults#egg=eppy
    - geomeppy
    - deprecation
    - sigfig
    - -r file:requirements-dev.txt