name: archetypal
channels:
  - defaults
dependencies:
  - shapely
  - matplotlib>=2.1
  - requests>=2.18
  - scikit-learn
  - scipy
  - pandas>=0.21
  - numpy>=1.13
  - tqdm
  - pip:
    - pycountry
    - eppy
    - geomeppy
    - pyomo
    - utm